### ISSUE TITLE
Proving usability of ActivityStreams2.0 and Microformats together by example

### ISSUE THREAD

**Issue by elf-pavlik** [w3c-social/social-web#1]
I see need for showcasing how to use ActivityStreams2.0 together with Microformats. I have impression that while AS2.0 focuses on Activities (~Events), Microformats already does Objects and as:Objects duplicates it in incompatible way instead of aligning with it.
Post recently written by @rhiaro has interesting insights very relevant to this issue http://rhiaro.co.uk/2015/04/post-and-activity-types
I would like to propose very pragmatic approach to find resolution for this issue:
1) @tantek - **one of Social WG chairs** uses Microformats in his deployment
2) @evanp - **one of Social WG chairs** uses ActivityStreams in his deployment

Reaching basic interoperability between two of our dear chairs will prove that we stay on tracks and don't wonder off in incompatible directions. Argument that we need federation component for that I would consider invalid. The Web will not break apart if to get started their deployments simply pull each other feed(s) and/or stream(s) even every second.

I would suggest starting demoing user stories which both of them +1
https://www.w3.org/wiki/Socialwg/Social_API/Sorting_user_stories

Also Micropub and ActivityPump look very close to each other and use two simple endpoints: Micropub/Outbox & Webmention/Inbox more early comparisons available at https://www.w3.org/wiki/Socialwg/Social_API/Comparison#Endpoint

**Comment by elf-pavlik** [comment]
http://socialwg.indiewebcamp.com/irc/social/2015-05-26/line/1432664342259

**Comment by akuckartz** [comment]
I have not seen anything "rude" or "condescending" and think that this characterisation and reaction is not justified.
